services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    

  minio:
    extends:
      file: docker-compose.yml
      service: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    

  app:
    extends:
      file: docker-compose.yml
      service: app
    build:
      context: ../app
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    restart: unless-stopped
    

  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      context: ../web
      dockerfile: Dockerfile
      target: development
    ports:
      - "80:3000"
    environment:
      - VITE_API_BASE=http://localhost:8080
    volumes:
      - ../web:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    

volumes:
  db_data:
    name: lisa-gallery-db-data
  minio_data:
    name: lisa-gallery-minio-data

networks:
  default:
    name: lisa-gallery-internal
  
