name: portfolio-lisa

services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    

  minio:
    extends:
      file: docker-compose.yml
      service: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    

  app:
    extends:
      file: docker-compose.yml
      service: app
    build:
      context: ..
      dockerfile: deploy/Dockerfile.app
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ../db/migrations:/app/migrations:ro
    restart: unless-stopped
    

  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      context: ../web
      dockerfile: ../deploy/Dockerfile.web
      target: development
    ports:
      - "80:8080"
    volumes:
      - ../web/src:/usr/src/app/src
      - ../web/public:/usr/src/app/public
      - ../web/index.html:/usr/src/app/index.html
      - ../web/vite.config.ts:/usr/src/app/vite.config.ts
      - ../web/tsconfig.json:/usr/src/app/tsconfig.json
      - ../web/tsconfig.app.json:/usr/src/app/tsconfig.app.json
      - ../web/tsconfig.node.json:/usr/src/app/tsconfig.node.json
      - ../web/tailwind.config.ts:/usr/src/app/tailwind.config.ts
      - ../web/postcss.config.js:/usr/src/app/postcss.config.js
      - ../web/components.json:/usr/src/app/components.json
    restart: unless-stopped
    

volumes:
  db_data:
    name: portfolio-lisa-db-data
  minio_data:
    name: portfolio-lisa-minio-data

networks:
  default:
    name: portfolio-lisa-internal
  
